# Generated by Django 3.0 on 2019-12-05 07:53

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=500, verbose_name='Location City')),
                ('state', models.CharField(max_length=500, verbose_name='Location State')),
                ('country', models.CharField(default='India', max_length=500, verbose_name='Location Country')),
                ('loc', models.TextField(verbose_name='Meta data')),
                ('uid', models.UUIDField(default='59a71f6520a37e3f37c667399e6f24c4', editable=False, verbose_name='Master Plant Uid')),
                ('timestamp_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('timestamp_modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterSku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Sku Name')),
                ('ul', models.PositiveIntegerField(verbose_name='Sku Ul')),
                ('ll', models.PositiveIntegerField(verbose_name='Sku ll')),
                ('uid', models.UUIDField(default='b2985086add1a06effc31adfcf5929cd', editable=False, verbose_name='Master Plant Uid')),
                ('timestamp_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('timestamp_modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Master Plant Name')),
                ('uid', models.UUIDField(default='e611aaad92bd2eb6d04add59431d8194', editable=False, verbose_name='Master Plant Uid')),
                ('timestamp_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('timestamp_modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Location', verbose_name='Plant Location')),
            ],
        ),
        migrations.CreateModel(
            name='MasterMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000, verbose_name='Machine NAME')),
                ('uid', models.UUIDField(default='9db652ac6fa5ad21ed4396eb31b84d99', editable=False, verbose_name='Master Plant Uid')),
                ('timestamp_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('timestamp_modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MasterPlant', verbose_name='plant')),
            ],
        ),
        migrations.CreateModel(
            name='MachineDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_weight', models.CharField(max_length=200, verbose_name='Box Weight')),
                ('timestamp', models.CharField(max_length=200, verbose_name='Timestamp')),
                ('pass_status', models.CharField(choices=[('accept', 'accept'), ('reject', 'reject')], max_length=100, verbose_name='Pass Status')),
                ('box_count', models.PositiveIntegerField()),
                ('uid', models.UUIDField(default='32cde66f57b06141ca2eb6ee419df79c', editable=False, verbose_name='Master Plant Uid')),
                ('timestamp_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('timestamp_modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MasterMachine', verbose_name='Master Machine')),
                ('sku', models.ManyToManyField(to='api.MasterSku', verbose_name='Sku Id')),
            ],
        ),
    ]
