# Generated by Django 3.0 on 2019-12-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191205_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mastersku',
            old_name='name',
            new_name='sku_id',
        ),
        migrations.AlterField(
            model_name='location',
            name='uid',
            field=models.UUIDField(default='e77eeb0d2cb49338ee41149216f772d9', editable=False, verbose_name='Master Plant Uid'),
        ),
        migrations.AlterField(
            model_name='machinedetail',
            name='uid',
            field=models.UUIDField(default='bf97879427c452160067bf2a54a4cca4', editable=False, verbose_name='Master Plant Uid'),
        ),
        migrations.AlterField(
            model_name='mastermachine',
            name='uid',
            field=models.UUIDField(default='b6acee7e2667c7026a1a21bbd1501a0b', editable=False, verbose_name='Master Plant Uid'),
        ),
        migrations.AlterField(
            model_name='masterplant',
            name='uid',
            field=models.UUIDField(default='9ec31a049bd7174adecfdd199570897b', editable=False, verbose_name='Master Plant Uid'),
        ),
        migrations.AlterField(
            model_name='mastersku',
            name='uid',
            field=models.UUIDField(default='1173aee91a2e7ee36e604be329160de7', editable=False, verbose_name='Master Plant Uid'),
        ),
    ]
