# Generated by Django 3.0 on 2019-12-05 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191205_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='uid',
            field=models.UUIDField(default='87d7290f354cd68aae8a2f6aaec62624', editable=False, verbose_name='Master Plant Uid'),
        ),
        migrations.RemoveField(
            model_name='machinedetail',
            name='sku',
        ),
        migrations.AddField(
            model_name='machinedetail',
            name='sku',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.MasterSku', verbose_name='Sku Id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machinedetail',
            name='uid',
            field=models.UUIDField(default='e0ea957fcc0115e1f3c4f16efe9a211b', editable=False, verbose_name='Master Plant Uid'),
        ),
        migrations.AlterField(
            model_name='mastermachine',
            name='uid',
            field=models.UUIDField(default='808316a72e24a5772ed20a2a3b2b9a57', editable=False, verbose_name='Master Plant Uid'),
        ),
        migrations.AlterField(
            model_name='masterplant',
            name='uid',
            field=models.UUIDField(default='ae113c377e7dc6056a676b730cd51edf', editable=False, verbose_name='Master Plant Uid'),
        ),
        migrations.AlterField(
            model_name='mastersku',
            name='uid',
            field=models.UUIDField(default='7bb35750ec3391728616cec1198d5b5c', editable=False, verbose_name='Master Plant Uid'),
        ),
    ]
