# Generated by Django 3.0 on 2019-12-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191205_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='uid',
            field=models.UUIDField(default='6bf364192bc745f2d55dba5edc561df3', editable=False, verbose_name='Master Plant Uid'),
        ),
        migrations.AlterField(
            model_name='machinedetail',
            name='uid',
            field=models.UUIDField(default='b7444f696e49fa0a5d99402369aa7429', editable=False, verbose_name='Master Plant Uid'),
        ),
        migrations.AlterField(
            model_name='mastermachine',
            name='uid',
            field=models.UUIDField(default='984682c1587efc11f62d18db3e5ddc33', editable=False, verbose_name='Master Plant Uid'),
        ),
        migrations.AlterField(
            model_name='masterplant',
            name='uid',
            field=models.UUIDField(default='cf7bc238dbe83adfada1a7d1f6b06092', editable=False, verbose_name='Master Plant Uid'),
        ),
        migrations.AlterField(
            model_name='mastersku',
            name='uid',
            field=models.UUIDField(default='16c89f8e3ef4f27bf4dfe1e992544d99', editable=False, verbose_name='Master Plant Uid'),
        ),
    ]
