# Generated by Django 3.0 on 2019-12-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191206_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='uid',
            field=models.CharField(default='e42323b8afae367ea8fa41df53f688f4', editable=False, max_length=50, verbose_name='Master Plant Uid'),
        ),
        migrations.AlterField(
            model_name='machinedetail',
            name='uid',
            field=models.CharField(default='da9f36021555a1279775071d6d876742', editable=False, max_length=50, verbose_name='Master Plant Uid'),
        ),
        migrations.AlterField(
            model_name='mastermachine',
            name='uid',
            field=models.CharField(default='c65ebbc0cc343156fc8af8c31c29c433', editable=False, max_length=50, verbose_name='Master Plant Uid'),
        ),
        migrations.AlterField(
            model_name='masterplant',
            name='uid',
            field=models.CharField(default='8cae440e0283fd3d420d041bce2e8bef', editable=False, max_length=50, verbose_name='Master Plant Uid'),
        ),
        migrations.AlterField(
            model_name='mastersku',
            name='uid',
            field=models.CharField(default='4a55ff78d4f232e75cd55652733676c8', editable=False, max_length=50, verbose_name='Master Plant Uid'),
        ),
    ]
