# Generated by Django 3.0 on 2019-12-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191206_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='uid',
            field=models.CharField(default='e428f87284d8d6bf037a14ac22ef8a59', editable=False, max_length=50, verbose_name='Master Plant Uid'),
        ),
        migrations.AlterField(
            model_name='machinedetail',
            name='uid',
            field=models.CharField(default='6a265f7477bbb803df65a252478b0b3d', editable=False, max_length=50, verbose_name='Master Plant Uid'),
        ),
        migrations.AlterField(
            model_name='mastermachine',
            name='uid',
            field=models.CharField(default='4568883cde20e5affa99fb06591fa21f', editable=False, max_length=50, verbose_name='Master Plant Uid'),
        ),
        migrations.AlterField(
            model_name='masterplant',
            name='uid',
            field=models.CharField(default='ef6250a445453161c76a1d860e80a576', editable=False, max_length=50, verbose_name='Master Plant Uid'),
        ),
        migrations.AlterField(
            model_name='mastersku',
            name='uid',
            field=models.CharField(default='7bb6c78a9cce991e14205c34a9b71d8b', editable=False, max_length=50, verbose_name='Master Plant Uid'),
        ),
    ]
