# Generated by Django 3.0 on 2019-12-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20191206_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='uid',
            field=models.CharField(default='3cfb834a4feea53290977431cfad081c', editable=False, max_length=50, verbose_name='Master Plant Uid'),
        ),
        migrations.AlterField(
            model_name='machinedetail',
            name='uid',
            field=models.CharField(default='8965e3f778a148922a144db7d002a8ec', editable=False, max_length=50, verbose_name='Master Plant Uid'),
        ),
        migrations.AlterField(
            model_name='mastermachine',
            name='uid',
            field=models.CharField(default='6620a0c7b9c49531c20459c36c736847', editable=False, max_length=50, verbose_name='Master Plant Uid'),
        ),
        migrations.AlterField(
            model_name='masterplant',
            name='uid',
            field=models.CharField(default='976910dd5c5f8c614e4278d553e9077c', editable=False, max_length=50, verbose_name='Master Plant Uid'),
        ),
        migrations.AlterField(
            model_name='mastersku',
            name='uid',
            field=models.CharField(default='add828113d60e1db53f6f33f9a517523', editable=False, max_length=50, verbose_name='Master Plant Uid'),
        ),
    ]
