# Generated by Django 3.0 on 2019-12-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191207_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersku',
            name='name',
            field=models.CharField(default='sku', max_length=200),
        ),
    ]
