# Generated by Django 3.0 on 2019-12-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_mastersku_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterplant',
            name='seial_number',
            field=models.CharField(default='', max_length=50, verbose_name='Serial Number'),
            preserve_default=False,
        ),
    ]
