# Generated by Django 3.0 on 2019-12-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_userprofile_plant_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='staff_user',
            field=models.BooleanField(default=False),
        ),
    ]
